### ISSUE TITLE
rad issue list (pipe)

### ISSUE THREAD

**Issue by d4ndo** [radicle-dev/radicle#643]
How come i can NOT pipe the output of `rad issue list`?

e.G.

`rad patch list | tail -n1`
or
`rad issue list 2> >(tail -n1)`

tail is ignored.

**Comment by jkarni** [comment]
We have an issue in `rad issue` for this - I'll paste it here for everyone else (sorry we're still in this weird in-between mode):

```
open 1 Don't use /dev/tty for script output Julian K. Arni 2019-03-11T16:39:07Z  

**State:** open
**Labels:** []

Currently things like `rad issue list | wc -l` won't work, since we're outputting directly to tty. That sucks. 

(As a note, in the meantime `script -q -c 'rad issue list'` can be used

Comments
--------

```

This is happening because we use the same code path for the repl and normal scripts, and just check what stdin is to decide whether to output to `/dev/tty`. That needs to be fixed, but for now, you can either use the `script` solution above, or more simply, add an `echo '' |` to the beginning of your pipe:

`echo '' | rad patch list | tail -n1`
